/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package momento.client.example;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() throws IOException {
    Library classUnderTest = new Library();
    assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
  }
}
