name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  javascript:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Deps and Build
        run: |
          pushd javascript
            npm ci
            npm run build
          popd

  java:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: |
          pushd java
            chmod +x gradlew
          popd

      - name: Build with Gradle
        run: |
          pushd java
            ./gradlew clean build
          popd

  csharp:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Configure Artifactory
        run: |
          set -e
          set -x
          dotnet nuget add source https://momento.jfrog.io/artifactory/api/nuget/nuget-public --name Artifactory
        shell: bash

      - name: Build
        run: |
          pushd dotnet/MomentoExamples
            dotnet build
          popd
        shell: bash

  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rustfmt
        run: cargo fmt -- --check
      - name: Rigorous lint via Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: |
          pushd rust
            cargo build --verbose
          popd
