name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]

jobs:
  typescript:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: dummy

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Configure Artifactory credentials
        run: |
          # lel this is how jfrog wants you to come up with your scoped npm configuration
          echo @momento:registry=https://momento.jfrog.io/artifactory/api/npm/npm-public/ >> ~/.npmrc

      - name: Install Deps and Build
        run: |
          pushd typescript
            npm ci
            npm run build
          popd

  java:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          pushd java
            ./gradlew clean build
          popd
